spring:
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://localhost:8081  # <-- Direct URL to product-service
          predicates:
            - Path=/api/products/**
        - id: order-service-route
          uri: http://localhost:8082  # <-- Direct URL to order-service
          predicates:
            - Path=/api/orders/**
        - id: front-api-route
          uri: http://localhost:8083  # <-- Direct URL to front-api
          predicates:
            - Path=/api/front/**
