spring:
  config:
    import: optional:configserver: # <-- AJOUTEZ CETTE LIGNE
  datasource:
    url: jdbc:mysql://localhost:3306/db_produits?serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
